### ISSUE TITLE
TEST_COUNTS not working anymore

### ISSUE THREAD

**Issue by sebzimmermann** [jenkinsci/hipchat-plugin#100]
Hi,

since some of the last upgrades, the TEST_COUNTS var aren't working anymore.

Before, the output was something like this:
```
PROJ-DTO #123 Build successful after 15 sec (Open) - Tests: 25 - Failed: 0
```

Now it looks like this:
```
PROJ-DTO #123 Build successful after 15 sec (Open) - Tests: ${TEST_COUNTS,var="total"} - Failed: ${TEST_COUNTS,var="fail"}
``` 

Any hints on how to fix this issue?

Jenkins version: 2.48
Plugin Version: 2.1.1

**Comment by aldaris** [comment]
Hmm, that sounds very strange. The TEST_COUNTS macro comes from the email-ext Jenkins plugin. I wonder if you have recently updated plugin or if you have it installed at the moment? Do you see TEST_COUNTS listed in the help message corresponding to the template settings?

**Comment by sebzimmermann** [comment]
Mailer Plugin is installed:
![image](https://cloud.githubusercontent.com/assets/1244654/23659393/4b8dcd22-0346-11e7-940a-f582dc3ea51c.png)

And is activated aswell (even though recepient list is empty as we don't want to send mails). 
![image](https://cloud.githubusercontent.com/assets/1244654/23659753/73946672-0347-11e7-9cbd-c7692b421ec5.png)


I don't see TEST_COUNTS listed in the help messages (is not derived from ${ENV,var="VARIABLENAME"}?).

**Comment by aldaris** [comment]
You need this plugin:
![email-ext](https://cloud.githubusercontent.com/assets/206692/23659868/7ea6bd9c-033f-11e7-927c-5ba8c1aa794e.png)

As long as the help text does not list the TEST_COUNTS token, it is not expected to work either.

**Comment by sebzimmermann** [comment]
Ah, now it's working as expected! Thank you very much!

**Comment by aldaris** [comment]
I will update the documentation so that it becomes clear that certain tokens are only available via other Jenkins plugins.
