### ISSUE TITLE
Plugin requires 1.609.2 but dependencies are requiring

### ISSUE THREAD

**Issue by aheritier** [jenkinsci/hipchat-plugin#102]
Warning: This plugin requires dependent plugins that are built for Jenkins 1.609.3 or newer. The dependent plugins may or may not work in your Jenkins and consequently this plugin may or may not work in your Jenkins.

Using a script like this with a 1.609.2 instance

```
def displayRequirements(dependencies) {
  dependencies.each{
		println "${it.shortName} ${Jenkins.instance.pluginManager.getPlugin(it.shortName).info.neededDependenciesRequiredCore}"
    	displayRequirements(Jenkins.instance.pluginManager.getPlugin(it.shortName).dependencies)
	}
}

displayRequirements(Jenkins.instance.pluginManager.getPlugin("hipchat").dependencies)
```

It shows

```
* antisamy-markup-formatter 1.565.3
* credentials 1.609
* display-url-api 1.609.3
* junit 1.580.1
* matrix-auth 1.609.1
* matrix-project 1.609
* plain-credentials 1.609
* script-security 1.580.1
* token-macro 1.609.2
* windows-slaves 1.580.1
* workflow-step-api 1.609.3
```

Thus culprits are display-url-api and workflow-step-api

**Comment by aldaris** [comment]
Thanksfor sharing your script, and going the extra mile on this one. I'll update the pom to depend on 1.609.3 instead.
