### ISSUE TITLE
Message template tokens not available in pipeline

### ISSUE THREAD

**Issue by perrefe** [jenkinsci/hipchat-plugin#103]
I'm trying to use tokens like BLUE_OCEAN_URL or HIPCHAT_CHANGES_OR_CAUSE within hipchatSend step message parameter in a declarative pipeline but their values are always null.

The step looks like:

```
hipchatSend (color: 'RED', notify: true, room: '123', token: 'abc', textFormat: false, message: "${JOB_NAME} [#${BUILD_NUMBER}] FAILED after ${env.HIPCHAT_CHANGES} and ${env.HIPCHAT_CHANGES_OR_CAUSE} (<a href=${env.BUILD_URL}/console>View log</a>)")
```

And the hipchat message is:

```
job [#13] FAILED after null and null (View log)
```

**Comment by aldaris** [comment]
You should probably use single quotes around the message parameter value, and the HipChat specific tokens are not stored as environment variables. You should use them like $HIPCHAT_CHANGES  and $HIPCHAT_CHANGES_OR_CAUSE instead..

**Comment by perrefe** [comment]
woah! Single quotes did the trick! I used to put double quotes when a templatable String were needed because of variable substitution.

Thanks!
