### ISSUE TITLE
Pipeline: Send build OK messages only if previous build failed.

### ISSUE THREAD

**Issue by ftclausen** [jenkinsci/hipchat-plugin#104]
We don't want to spam everyone in the channel every time there is a successful build when using the Jenkins multi-branch pipeline - we just want to know when builds fail and then when they recover. Ideally the following behaviour:

* Failure: Send notification about every failed build
* Success: Only send a notification if the previous build was failing and this build makes things green again

**Comment by aldaris** [comment]
And that's exactly what the Back to Normal notification type is all about. Have you tried using that?

**Comment by ftclausen** [comment]
Can you give me an example of how to use that in Pipeline code? Sorry, my initial issue description was not clear that I was using Pipeline.

**Comment by aldaris** [comment]
Pipeline build is a different kind of animal, you will have to write your pipeline script to accommodate this requirement.
See:
https://support.cloudbees.com/hc/en-us/articles/226419147-How-can-I-check-previous-build-status-in-a-Pipeline-Script-
http://stackoverflow.com/questions/40284904/jenkins2-get-previous-build-result

**Comment by ftclausen** [comment]
Thanks! I'll take a look at those examples. You can close this issue.
