### ISSUE TITLE
Notifications are randomly sent to hipchat

### ISSUE THREAD

**Issue by TomGudman** [jenkinsci/hipchat-plugin#105]
Hi,

## Context
- Jenkins 2.54
- Hipchat plugin 2.1.1

## Description
Hipchat messages are not sent (or plugin is not executed at all...)
Statistically, it seems 'build failed" notifications go through 90% of the time while 'build success' notifications only reach hipchat 5% of the time. It is really an odd behaviour; it is random. It seems to only affect new projects but I am not 100% sure about that either.

## Setup
- Build failed in red 
- Build success in green
- Default template values (but I did first try with templated messages for failed and successful builds and then replaced them by just one for completed to finally removed it to only use defaults due to these missing hipchat messages driving me nuts)

## Consequences
- Missing hipchat message
- Missing [Hipchat] logline in the console output (looks like it is not executed at all)

## Config.xml 
```
 <publishers>
    <htmlpublisher.HtmlPublisher plugin="htmlpublisher@1.12">
      <reportTargets>
        <htmlpublisher.HtmlPublisherTarget>
          <reportName>ScalaTest Report</reportName>
          <reportDir>target/htmldir</reportDir>
          <reportFiles>index.html</reportFiles>
          <alwaysLinkToLastBuild>false</alwaysLinkToLastBuild>
          <keepAll>false</keepAll>
          <allowMissing>true</allowMissing>
        </htmlpublisher.HtmlPublisherTarget>
        <htmlpublisher.HtmlPublisherTarget>
          <reportName>Coverage Report</reportName>
          <reportDir>target/scala-2.11/scoverage-report</reportDir>
          <reportFiles>index.html</reportFiles>
          <alwaysLinkToLastBuild>false</alwaysLinkToLastBuild>
          <keepAll>false</keepAll>
          <allowMissing>true</allowMissing>
        </htmlpublisher.HtmlPublisherTarget>
      </reportTargets>
    </htmlpublisher.HtmlPublisher>
    <hudson.tasks.junit.JUnitResultArchiver plugin="junit@1.20">
      <testResults>target/report/*.xml</testResults>
      <keepLongStdio>false</keepLongStdio>
      <healthScaleFactor>1.0</healthScaleFactor>
      <allowEmptyResults>true</allowEmptyResults>
    </hudson.tasks.junit.JUnitResultArchiver>
    <jenkins.plugins.hipchat.HipChatNotifier plugin="hipchat@2.1.1">
      <credentialId>HipChat-API-Token</credentialId>
      <room>Jenkoins</room>
      <notifications>
        <jenkins.plugins.hipchat.model.NotificationConfig>
          <notifyEnabled>true</notifyEnabled>
          <textFormat>false</textFormat>
          <notificationType>SUCCESS</notificationType>
          <color>GREEN</color>
          <messageTemplate></messageTemplate>
        </jenkins.plugins.hipchat.model.NotificationConfig>
        <jenkins.plugins.hipchat.model.NotificationConfig>
          <notifyEnabled>true</notifyEnabled>
          <textFormat>false</textFormat>
          <notificationType>FAILURE</notificationType>
          <color>RED</color>
          <messageTemplate></messageTemplate>
        </jenkins.plugins.hipchat.model.NotificationConfig>
      </notifications>
      <startJobMessage></startJobMessage>
      <completeJobMessage>$JOB_NAME - v$PROJECT_VERSION - #${BUILD_NUMBER} ${GIT_BRANCH}-${GIT_REVISION,length=8} - $STATUS after $BUILD_DURATION (&lt;a href=&quot;$BUILD_URL&quot;&gt;View build&lt;/a&gt;)</completeJobMessage>
    </jenkins.plugins.hipchat.HipChatNotifier>
  </publishers>
```
Once the completeJobMessage parameter is removed the behaviour remains the same except that sometimes (2 out of 3 tests) when I changed the hipchat config it seems that 'build successful' notification went through. Could be just luck but it seemed related. Spent 2h+ trying to understand the issue; it is hard to objective anymore. 

## Logs
- Job Console output displays a message line when the message is sent successfully to hipchat
- Job Console displays nothing like the hipchat plugin was not executed at all when the message never reaches Hipchat
- Jenkins logs do not show any issues. 

## Possible cause
- Use of non standard message template

## References
- https://issues.jenkins-ci.org/browse/JENKINS-43060

**Comment by aldaris** [comment]
Build success notifications are only sent when the build result is success and the previous build result was also success.
If the previous build result was something else than success, the notification type will be "back to normal" instead.

**Comment by TomGudman** [comment]
What about the first build? It did not sent any success notification for the first time we build it (e.g: Job #1 is successful)

**Comment by aldaris** [comment]
Since https://github.com/jenkinsci/hipchat-plugin/blob/master/src/main/java/jenkins/plugins/hipchat/model/NotificationType.java#L136 doesn't check if previousResult was null, I guess it would be considered back to normal. That looks like a bug.

**Comment by TomGudman** [comment]
Ok cool. We are happy to test when you have the time to release a new version

Thank you for the explanation about 'Back to normal', we never used it and never understood its purpose and never realised its consequence until now. I will have to update all our jobs to support that.

**Comment by TomGudman** [comment]
FYI, since I have 'back to normal', the first build now sends a notification with a message 'Back to normal'. As you said it should technically be a 'build success' message instead.
