### ISSUE TITLE
Pipeline Url Link support

### ISSUE THREAD

**Issue by ksaraie** [jenkinsci/hipchat-plugin#107]
I would like the URL of the build to be an actual link to the build instead of the string url.
hipchatSend(message: "Pipeline Master FAILED: #${env.BUILD_NUMBER} (${env.BUILD_URL})")
is shown as:
Pipeline Master FAILED: #18 (https://jenkins.com/job/master/18/)

**Comment by aldaris** [comment]
Then send the notification as HTML and put the URL into an "a" tag:

    hipchatSend(message: "Pipeline Master FAILED: #${env.BUILD_NUMBER} (<a href=\"${env.BUILD_URL})\">Open</a>")

**Comment by aldaris** [comment]
Closing as not a defect. :)
