### ISSUE TITLE
Support Hipchat v2

### ISSUE THREAD

**Issue by bstascavage** [jenkinsci/hipchat-plugin#11]
Right now your plugin only supports API Version 1.  Would be great if you provide support for API Version 2.

**Comment by jikamens** [comment]
Here's a "rela-life use case of the v2 support": Apparently as of now HipChat is no longer supporting v1, so our HipChat notifications are no longer working. At All. I think "make it work the way it used to" is a pretty compelling use case. ;-)

**Comment by jikamens** [comment]
Please disregard my comment above. I was wrong about HipChat discontinuing support for API v1. I was running into other issues (#29, #30) which were preventing notifications from being sent as we expected them to.

**Comment by aldaris** [comment]
v2 support is *finally* implemented with 053c2c6
Thanks for your patience!
