### ISSUE TITLE
Allow the build message to contain the branch

### ISSUE THREAD

**Issue by jdmarshall** [jenkinsci/hipchat-plugin#13]
On projects with multiple branches it can be difficult to tell whether a build failure is yours or someone else's.  Having the branch in the Hipchat message would help.

**Comment by aaboyd** [comment]
You can use $GIT_BRANCH inside the message template and it will show you which branch was built.

**Comment by aldaris** [comment]
Agree, using $GIT_BRANCH sounds like a good approach.
