### ISSUE TITLE
Add support for comments file display from Github Pull Request plugin

### ISSUE THREAD

**Issue by podarok** [jenkinsci/hipchat-plugin#15]
Hi
Thanks for the great plugin

A Little suggestion
Message, posted by the plugin is not so informative and leads to jenkins UI console which is not convenient for everyday usage.
When there is a workflow based on GitHub pull request plugin, every job has it's own commentinfo file (Text file), which contains links to usefull resources for review before merging. That file automatically attached to github comment after build. It would be nice to get this text into message for Hipchat too.

**Comment by aldaris** [comment]
Unfortunately even after reading the issue description several times, I have literally no idea what the proposed feature is, or even how to come up with an environment where I could test any of this. :(
