### ISSUE TITLE
Please add the ability for green messages to notify

### ISSUE THREAD

**Issue by StuartWhelan** [jenkinsci/hipchat-plugin#16]
We would like for sucessfull build to still notify hipchat users when the build finishes.

We want it on a project by project basis

**Comment by aldaris** [comment]
Conflicting request with [JENKINS-28314](https://issues.jenkins-ci.org/browse/JENKINS-28314). I think the solution will be to have a *single* checkbox that says notify or not notify and that will determine the notification mode for ALL notification types.

**Comment by a-umaniuc** [comment]
+1

**Comment by aldaris** [comment]
This is now possible since the configuration refactor: 32f1ca7
