### ISSUE TITLE
Be able to customise the HipChat notification message at the job level

### ISSUE THREAD

**Issue by BrunoLavitForgerock** [jenkinsci/hipchat-plugin#25]
This plugin is very helpful to notify our developers and QAs.
To improve the notification, we would like to be able to customise the HipChat notification message at the job level.
With this custom message, we could be able to use some Jenkins or Maven properties: https://blog.codecentric.de/en/2014/07/accessing-maven-project-properties-jenkins-build-jobs/
If a custom message is set at the job level, the plugin should use it.
Otherwise, the plugin should use the default message (like today).
Thanks to the hipchat-plugin team :)

**Comment by rouge8** [comment]
jlewallen/jenkins-hipchat-plugin#45 also looks promising

**Comment by retoo** [comment]
@aldaris please see my pull request. Let me know if you require any changes :).

**Comment by mstanleyjones** [comment]
I'd like to vote for this too.
