### ISSUE TITLE
room setting and notification selection should be per post-build task, not per build

### ISSUE THREAD

**Issue by jikamens** [jenkinsci/hipchat-plugin#29]
Right now there's a HipChat configuration setting in each build, where you specify the room (to override the default) and which notifications to send, regardless of whether the HipChat post-build action is enabled for the build.

This configuration should be per-post-build-action, not per-build, for two reasons:

1. It is quite misleading to have that configuration at the top of the build configuration page when it doesn't actually do anything unless there is a HipChat post-build action configured for the build.

2. Putting the config per-action rather than per-build would allow different types of notifications to be sent to different rooms.

**Comment by aldaris** [comment]
I believe this is already resolved with bb103a3.

**Comment by aldaris** [comment]
Feel free to check out the latest nightly, should work much better.
