### ISSUE TITLE
There should be default notification selections

### ISSUE THREAD

**Issue by jikamens** [jenkinsci/hipchat-plugin#30]
I shouldn't have to specify separately in every single build job which HipChat notifications I want. Just like there is a default room specifier and a default API key specifier configuration, there should also be a default selection of which notifications to send.

**Comment by aldaris** [comment]
At this stage this is unlikely to get implemented:
The settings are booleans, hence they only have two states, and it is a bit more difficult to determine whether a setting is simply not set, or just set to "false". Maybe a proposed solution would be to check if none of the notifications are enabled in the job configuration and then try to fall back to the global settings, but this all sounds a bit tedious for something that probably can be scripted anyways.
Maybe this is something that gets tackled with JENKINS-18120, but no idea just yet.

**Comment by aldaris** [comment]
This wasn't quite intentional, but the new configuration mechanism now allows this, see 32f1ca7
