### ISSUE TITLE
Job configuration won't get updated when global configuration changes

### ISSUE THREAD

**Issue by Fantoccini** [jenkinsci/hipchat-plugin#31]
Hi there,
Thanks for the great plugin.

I found an issue that: if you change the hipchat global configuration in "Manage Jenkins", such as the "send as" name. The job configuration(./jobs/job_name/config.xml) won't change, as the result they still use the old name to send messages.

Jenkins version: 1.596 running on ubuntu server 14.04
Plugin version: 0.1.8

Thanks.

**Comment by aldaris** [comment]
Thanks for raising this issue, will have a look and try to reproduce it locally. Modifying the global settings shouldn't really result in changes to be persisted in the job settings, but I would expect the new global settings being picked up from the notifier..

**Comment by diasjorge** [comment]
I have changed the url of the jenkins server and even when I change the buildServerUrl in the general settings the jobs still send the links with the old url

**Comment by gena01** [comment]
Is it possible NOT to store the sensitive information in the Job config.xml? It's a security risk and can leak system config/token.

**Comment by aldaris** [comment]
@gena01 please open a new issue for this.

**Comment by retoo** [comment]
I think this has been resolved too. On master the plugin seems to behave correctly.

**Comment by aldaris** [comment]
This should be all resolved now with the latest nightly.
