### ISSUE TITLE
Please release a new version

### ISSUE THREAD

**Issue by retoo** [jenkinsci/hipchat-plugin#32]
Deploying the latest version (master) on our jenkins enabled us to get the plugin working. Can you please make a new release?

**Comment by aldaris** [comment]
I've got a work in progress implementation of the v2 API support, which I couldn't really test too much just yet. I'll look into tidying that work up and get it committed, but I don't want to release the plugin without some extra testing first.

**Comment by retoo** [comment]
Let me know if I can test anything. We have a fairly busy hipchat/jenkins environment.

**Comment by gena01** [comment]
+1

**Comment by gena01** [comment]
@aldaris can we also get a security fix into the next release?

**Comment by aldaris** [comment]
@retoo Thanks for the offer, gonna take your word for it :) I've just got around to finalize my code for v2 API and notification refactors. Wouldn't say everything is in there, but I don't expect too many big changes going in now.

**Comment by aldaris** [comment]
At the moment my plan for this weekend to have a review of the notification message customization PR and then perform a release of 0.1.9. If you could run some tests, that would be really appreciated.

**Comment by retoo** [comment]
The custom notification branch was deployed in our environment this week and worked well. Including all the refactoring you did. But I couldn't get the v2 api working.

**Comment by aldaris** [comment]
I believe now all outstanding issues are resolved for the release. Next weekend I'll look into publishing 0.1.9.

**Comment by aldaris** [comment]
0.1.9 has been released this week, closing :)
