### ISSUE TITLE
Stop copying Global System parameters into job/config.xml

### ISSUE THREAD

**Issue by gena01** [jenkinsci/hipchat-plugin#33]
It appears that the plugin is copying the global settings for server and token into each job/config.xml. This has two separate issues:
1. Changing global system settings doesn't "fix" things until every job is re-saved. And things are broken until that step is performed.
2. It's possibly leaking sensitive information. All a user needs to have access to is to be able to create and manage job configs. Normally there's no way to set HipChat connection information in the Job Configuration page, but because of this bug they might be able to see something they shouldn't.

**Comment by gena01** [comment]
@aldaris done per comment in #31

**Comment by aldaris** [comment]
I haven't had much chance to look at this yet, but I'm wondering if any of my refactorings in master has already resolved by any chance. Could you give it a test and see if the authToken still makes it into the job configurations? Thanks

**Comment by retoo** [comment]
I think this has been resolved.

**Comment by aldaris** [comment]
During my local tests today I've got the same result. Closing this one as fixed in 0.1.9-SNAPSHOT
