### ISSUE TITLE
Not functioning with v1 or v2 API tokens

### ISSUE THREAD

**Issue by DavidR91** [jenkinsci/hipchat-plugin#34]
`HipChat post may have failed. Response: {"error":{"code":401,"type":"Unauthorized","message":"Auth token invalid. Please see: https:\/\/www.hipchat.com\/docs\/api\/auth"}}`

is all I get, regardless of v1 or v2. 

Even if I create a v1 token with admin permissions rather than notify, I still get the above response

This is with 0.1.8 available through Jenkins

**Comment by NeuralSandwich** [comment]
+1

**Comment by aldaris** [comment]
Works fine for me. 0.1.8 version of the plugin only supports v1 API so you should certainly not use v2 tokens.

**Comment by NeuralSandwich** [comment]
I have used both the notification and admin token for api v1 and it did not work. I kept receiving Error 401, for bad authentication.

**Comment by aldaris** [comment]
Could this be caused by #31?

**Comment by aldaris** [comment]
Closing as cannot reproduce, works fine for me. Possibly caused by #31
