### ISSUE TITLE
Root url is not used when posting build URLs

### ISSUE THREAD

**Issue by cmeury** [jenkinsci/hipchat-plugin#40]
Even though I have configured the root URL in "Manage Jenkins", the plugin posts URLs in the following format: https://xyz.hipchat.com/nulljob/projectname-7.0/1237/

**Comment by aldaris** [comment]
With which version of the plugin are you running into this behavior? Do you have a reverse proxy in front of Jenkins? If yes, how did you configure it?

**Comment by cmeury** [comment]
@aldaris Apologies for my rather terse initial report - I am running plugin version `0.1.8`. There is an nginx running in front of Jenkins which routes ports and terminates SSL. In the global configuration, I configured the "final" URL a client would use.

**Comment by aldaris** [comment]
I could only reproduce bad URLs like:

    <a href='nulljob/docbook-linktester/1/'>Open</a>

This happened because the configuration was incorrectly persisted with 0.1.8: a change made to the global setting required the affected projects to be resaved as well. Should work better now with 0.1.9-SNAPSHOT.

**Comment by cmeury** [comment]
Awesome, 0.1.9 fixed the issue - thanks a lot for your quick reaction @aldaris!
