### ISSUE TITLE
v2 API help message is incorrect

### ISSUE THREAD

**Issue by frewsxcv** [jenkinsci/hipchat-plugin#41]
https://github.com/jenkinsci/hipchat-plugin/blob/a1fad5b4a3023a805429848995a92e4c224c624b/src/main/resources/jenkins/plugins/hipchat/HipChatNotifier/global.jelly#L3-L8

Both entries share the same help message, which is probably not what we want

![screen shot 2015-03-13 at 2 36 27 pm](https://cloud.githubusercontent.com/assets/416575/6644927/5a257ff4-c98e-11e4-8df8-0aa9ea529f00.png)

**Comment by aldaris** [comment]
Note to self: same as https://issues.jenkins-ci.org/browse/JENKINS-27304
