### ISSUE TITLE
Send arbitrary messages from workflow or build flow Groovy DSL jobs

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/hipchat-plugin#43]
We have some jobs that use the 'build flow' plugin, which lets you configure the build using Groovy. In the past we have queued a dedicated parameterized Jenkins job, which just uses cURL to send arbitrary strings to the HipChat room we want. In a build flow we can use this to send messages at any point during the flow - "build started," "tests passed," "deploy completed," etc.

With the HipChat plugin, is there any way we could access the necessary plugin methods in Groovy to get a similar feature, so we could just call org.foo.HipChatplugin.newMessage("some-room", "this is a sample message string")  ? This would also be useful to users of the 'workflow' plugin, I would think.

**Comment by aldaris** [comment]
I've used the following DSL with build-flow plugin:

    def hipChatV1 = new jenkins.plugins.hipchat.impl.HipChatV1Service("api.hipchat.com", "v1_token", "room name list that can be separated by comma, or just a single room name", "sendAs");
    hipChatV1.publish("This is a V1 notification", "green", /*notify?*/true);
    def hipChatV2 = new jenkins.plugins.hipchat.impl.HipChatV2Service("api.hipchat.com", "v2_token", "room name list that can be separated by comma, or just a single room name");
    hipChatV2.publish("This is a V2 notification", "green", /*notify?*/true);

At least the API is currently looking like this. Potentially I'll add this to the plugin README so if the API changes that can be picked up. Note that if the API changes, your build will most certainly break.

**Comment by moserke** [comment]
This does not work in a sandbox script.  Any thoughts on using it in that mode?  We must use sandbox as we are in a shared Jenkins and don't have permissions to run not sandbox.

**Comment by kmadel** [comment]
See jenkinsci/hipchat-plugin/pull/60

**Comment by aldaris** [comment]
FYI #60 is now merged, if I'm not mistaken now both build-flow plugin and workflow-plugin has a working solution. Closing this issue.
