### ISSUE TITLE
Hipchat plugin does not allow to use build parameters

### ISSUE THREAD

**Issue by kenden** [jenkinsci/hipchat-plugin#44]
The plugin does not allow to use build parameters values.

I want to notify different Hipchat rooms depending on a parameter I pass to a jenkins job.

I set the value of the parameter when calling the job. In the Jenkins job config:
 - Checkbox: "This build is parameterized" is checked,
- Text parameter "HIPCHATROOM" added, with value 1332745,
- In "Hipchat Noficiations", "Project room" is set to ${HIPCHATROOM}

There is no Hipchat notifications when the build starts/fails/suceeds/etc.

Note: I DO get a notification if "Project room" is set to 1332745 in "In Hipchat Noficiations".

This is with version 0.1.9 of the plugin. (Jenkins ver. 1.599)
That version included https://github.com/jenkinsci/hipchat-plugin/issues/29, which has the Hipchat config BELOW/AFTER the Build parameters config. 0.1.8 did not work either).

**Comment by kenden** [comment]
I added a comment to this JIRA ticket: 
https://issues.jenkins-ci.org/browse/JENKINS-22723
JIRA seems to be the proper place for bugs

**Comment by aldaris** [comment]
This is now implemented with cfc8282
