### ISSUE TITLE
Notifications not working with build-flow-plugin

### ISSUE THREAD

**Issue by stephenmelrose** [jenkinsci/hipchat-plugin#45]
Hey,

Not sure if this is an issue with the hipchat-plugin or the build-flow-plugin, but I'm able to get notifications to work for build-flow jobs.

I've added the config for hipchat-plugin into Jenkins' "Configure System" and hit "Test configuration", and everything works.

I've added the post build notification to one of our "normal" jobs and it's working as expected. I've then added it to one of our build-flow-plugin jobs, which the vast majority of our jobs are, and they're not working.

I've tried multiple permutations with the settings, and nothing is working. Everything else does.

Any ideas?

Jenkins Version: 1.612
hipchat Version: 0.1.9
build-flow-plugin Version: 0.17

**Comment by aldaris** [comment]
No idea what's going on, I've never really used build-flow plugin. Will try to reproduce it in a clean environment.

**Comment by wcahillmanley** [comment]
I can also confirm this issue.

Jenkins version: 1.616
Hipchat version: 0.1.9
Buildflow version: 0.18

Just as stephenmelrose did, I tried multiple sets of settings and configurations. I was able to get hipchat notifications working from a job that gets called by the build flow plugin, but not from the flow itself.

**Comment by aldaris** [comment]
Looks like build-flow is getting more and more users, I guess this should be resolved for 0.2.0.

**Comment by aldaris** [comment]
build-flow notifies correctly when the "Flow run needs a workspace" option is enabled. Most likely the publisher doesn't get invoked for FlyweightTasks, not sure what can be done on that front...

**Comment by aldaris** [comment]
Looking at build-flow-plugin's source this appears to be intentional, the FlyweightTaskRunnerImpl does not call out to the publishers.
If having a workspace for the flow run is not doable, then I would suggest to follow #43 instead. There is not much I can do with this issue.
