### ISSUE TITLE
Silence from Hipchat plugin on likely failures

### ISSUE THREAD

**Issue by TimGebhardt** [jenkinsci/hipchat-plugin#46]
Hello, I just ran into an issue where I configured the Hipchat plugin on Jenkins and things were silently failing.  I didn't know if the plugin was working or not, but eventually I hooked up verbose logging and discovered that the user I was sending as was more than 15 characters.

My request is to output likely failure messages to the build log.

**Comment by aldaris** [comment]
Looks like this is a limitation of the v1 API:
https://www.hipchat.com/docs/api/method/rooms/message
I think it would be helpful if the config screen could warn about invalid value. To improve the error messages probably I'll work on #9 instead.

**Comment by aldaris** [comment]
FYI #9 is now resolved, so firstly the build log should now indicate if sending the notification has failed, but more importantly the Test Notification button now properly displays error messages.

**Comment by aldaris** [comment]
The UI is now a lot more friendlier and provides useful error messages when send As value is incorrect/missing. see 515bb96
