### ISSUE TITLE
Allow to select message format

### ISSUE THREAD

**Issue by btmash** [jenkinsci/hipchat-plugin#47]
Currently messages are strictly sent in html format. However, the disadvantage of this is that html messages lose special hipchat features (like notifications). Having a select box for the format would be immensely useful.

**Comment by aldaris** [comment]
The problem is that without the HTML format, providing links to the console looks a lot less nice..

**Comment by kopelli** [comment]
That may be, but sending over an HTML formatted message doesn't have any emoticon's parsed from it.

In our scenario, we wanted to include a custom emoticon as part of the message when a deployment job is started.

**Comment by aldaris** [comment]
On the other hand in HTML you should be use <img> tags.
If anything this will probably end up as a global setting.

**Comment by sbutalia** [comment]
It will be useful to have text format so we can set mentions. HipChat only allows mentions for text format.
