### ISSUE TITLE
Not Notified "Back to Normal" when build is Successful after it has been Aborted

### ISSUE THREAD

**Issue by tldavies** [jenkinsci/hipchat-plugin#51]
There is no notification that the build has gone back to normal after it has been aborted and is rerun and passed.

**Comment by aldaris** [comment]
This is now resolved with ff5c4d5

**Comment by tldavies** [comment]
Thanks!!
Do you know when the next upgrade will be with this new code?

**Comment by aldaris** [comment]
Not sure just yet, I'm still just going through the backlog.

**Comment by tldavies** [comment]
Thanks! I will keep a lookout for the next upgrade. :-)
