### ISSUE TITLE
Build completed message only after failure

### ISSUE THREAD

**Issue by Snorlock** [jenkinsci/hipchat-plugin#53]
Hi would it be possible to have a checkbox for build completed notifications but only after build has failed. Because build completed is not very important to us, except when the build has failed.

**Comment by aldaris** [comment]
I'm a bit confused, isn't the "Back to Normal" notification doing exactly that?

**Comment by Snorlock** [comment]
It was, just didnt know about it until after posting, im sorry for this issue.
