### ISSUE TITLE
Custom message per build status

### ISSUE THREAD

**Issue by mstanleyjones** [jenkinsci/hipchat-plugin#54]
I'd like the ability to send a custom message per build status. Specifically, I'd like to use Hipchat icons to the status message. Something like (greenbeer) for green, (poop) for red, and (facepalm) for yellow. There is no post-build shell step, or I could inject an environment variable and do the icon based on that. But I think it would be better if I could just set custom notifications instead of just one for start and one for end.

**Comment by aldaris** [comment]
Setting build messages per status is implemented now with 32f1ca7. However in order to use emoticons, you will need to watch #47.
