### ISSUE TITLE
Instruction for setting up

### ISSUE THREAD

**Issue by tnguyen14** [jenkinsci/hipchat-plugin#58]
I am trying to set up this plugin (version 0.2.0) for my Jenkins server to post notification to a HipChat room.

I've added the Hipchat room token and the room name, but it isn't working.

Could someone provide more detailed instruction on how to set up this plugin?

**Comment by aldaris** [comment]
I've just updated the Wiki page with configuration notes, let me know if it's helpful:
https://wiki.jenkins-ci.org/display/JENKINS/HipChat+Plugin

**Comment by tnguyen14** [comment]
Hi @aldaris, when I checked it on Sunday it wasn't there yet, but it seems to be published now. So thank you!

What I was missing was the global settings.

I added the "HipChat Server" and checked "Use v2 API", and it is working now. 
Note, I didn't set any global API token, and only use Room Token, and it was working for me. So I would perhaps add that in the doc as well.

**Comment by aldaris** [comment]
Thanks for the feedback, I've added the note for the API Token setting.

**Comment by tnguyen14** [comment]
Also small typo:

On this line
>Project Room: The comma separated list of rooms that needs to be modified about the build status.

I think you meant "notified", not "modified".

**Comment by aldaris** [comment]
Fixed
