### ISSUE TITLE
Changes variable

### ISSUE THREAD

**Issue by vad1m** [jenkinsci/hipchat-plugin#59]
Please allow to use $CHANGES variable with extended format (as email-ext plugin do), for example:

```
${CHANGES, showPaths=true, format="
[ %a ] %m", pathFormat="- %p"}
```

Now only $CHANGES can be parsed, but I want to publish changelog for each release.
Or maybe there is another option to post changelog in hipchat?

**Comment by aldaris** [comment]
With the introduction of token-macro support, this should be possible with 2.1.0.
