### ISSUE TITLE
Different rooms per notification

### ISSUE THREAD

**Issue by Alloc86** [jenkinsci/hipchat-plugin#66]
Hi,

currently we can only set a room per project (or globally) but we'd like to show failure messages only in a devs only room while a successful build is supposed to go to another room where our testers are chatting.
So it would be great if one could specify/override the target room for each notification individually.

Regards,
Chris

**Comment by aldaris** [comment]
I've got no plans to implement this unfortunately. The config UI is already a bit overcomplicated and this doesn't feel like a common request. If you need to implement this use-case nonetheless, I would suggest to use workflow/build-flow plugins and script the message sending according to the build results.
