### ISSUE TITLE
Is there a way to send private/direct messages to a user rather than a room?

### ISSUE THREAD

**Issue by omehegan** [jenkinsci/hipchat-plugin#70]
The subject says it all. I'd like to be able to send messages to an individual, rather than a room, because our rooms are getting polluted with notifications that only need to be seen by one person.

**Comment by aldaris** [comment]
I don't believe that this is possible, only users can send private messages to users. OAuth2 tokens issued to groups won't be able to do that. See https://www.hipchat.com/docs/apiv2/method/private_message_user

**Comment by omehegan** [comment]
My now-former coworker actually has a partially-complete pull request for the plugin which supports this. I've handed off the work to someone else, I hope to see it submitted pretty soon. It does require you to create a user and then create an API token for them with appropriate privileges.

**Comment by tomasbjerre** [comment]
You can do it with curl:
```
curl -H "Authorization: Bearer oasdasdasdasdasdasdasdFm"  -H "Content-Type: application/json" https://hipchat.asdasdasdasd.se/v2/user/tomas.bjerre@asdasdasdasd.se/message -X POST -d '{"message": "hej", "notify": "true", "message_format": "text"}
```
