### ISSUE TITLE
Issue with Build FLow Plugin

### ISSUE THREAD

**Issue by Razawalla** [jenkinsci/hipchat-plugin#71]
We had defined build flow as below:

**parallel (
     {
	build("pkr-ctr" , Variant:params.Variant)
        build("pkr-blg" , Variant:params.Variant)
        build("pkr-rtg" , Variant:params.Variant)
     },
     {build("pkr-jcc" , Variant:params.Variant)},
     {build("pkr-fln" , Variant:params.Variant , Environment:params.Environment)},
     {build("pkr-rts" , Variant:params.Variant)},
     {build("pkr-UI-rts" , Variant:params.Variant)},
     {build("pkr-JRules" , Variant:params.Variant)},
     {build("ABCD" , Variant:params.Variant)}
)
build("pkr-UI" , Variant:params.Variant , Environment:params.Environment)
**
We ran pkr_all_jobs.. though all the jobs were completed successfully, it still failed. please find below output:

**Result:

Started by user xxxxx
Building on master in workspace /opt/mdp/data/jenkins-d/workspace/vphad_test/DSL_plugin_test/pkr-All-Projects
parallel {
    Schedule job vphad_test » DSL_plugin_test » pkr-ctr
    Schedule job vphad_test » DSL_plugin_test » pkr-UI-rts
    Schedule job vphad_test » DSL_plugin_test » pkr-fln-pkr-sync-batch
    Schedule job vphad_test » DSL_plugin_test » pkr-jcc
    Schedule job vphad_test » DSL_plugin_test » pkr-fln
    Build vphad_test » DSL_plugin_test » pkr-ctr #4 started
    vphad_test » DSL_plugin_test » pkr-ctr #4 completed 
    Schedule job vphad_test » DSL_plugin_test » pkr-blg
    Build vphad_test » DSL_plugin_test » pkr-UI-rts #4 started
    Build vphad_test » DSL_plugin_test » pkr-fln-pkr-sync-batch #4 started
    vphad_test » DSL_plugin_test » pkr-fln-pkr-sync-batch #4 completed 
    Build vphad_test » DSL_plugin_test » pkr-fln #4 started
    vphad_test » DSL_plugin_test » pkr-UI-rts #4 completed 
    Build vphad_test » DSL_plugin_test » pkr-jcc #4 started
    vphad_test » DSL_plugin_test » pkr-jcc #4 completed 
    vphad_test » DSL_plugin_test » pkr-fln #4 completed 
    Build vphad_test » DSL_plugin_test » pkr-blg #4 started
    vphad_test » DSL_plugin_test » pkr-blg #4 completed 
    Schedule job vphad_test » DSL_plugin_test » pkr-rtg
    Build vphad_test » DSL_plugin_test » pkr-rtg #4 started
    vphad_test » DSL_plugin_test » pkr-rtg #4 completed 
}
Finished: FAILURE
**

On analysis we found that " pkr-JRules " was not triggered because there was "space bar" in the actual job name "" pkr JRules " where as in build flow it was defined as " pkr-JRules ".

Main problem: In the console output it is not showing the actual error
Please suggest.

**Comment by aldaris** [comment]
How exactly is this related to the HipChat plugin?

**Comment by Razawalla** [comment]
no it is build-flow-plugin

**Comment by aldaris** [comment]
Then I would suggest to raise this problem with them instead.
