### ISSUE TITLE
Missing help file for Notifications / Message template Row

### ISSUE THREAD

**Issue by mikelax** [jenkinsci/hipchat-plugin#73]
I am using version `1.0.0` of the plugin. 
I would like to view the help for the Message Format field so I know how I can create a custom message for certain notification statuses. 

When I click the ? icon, I get the following error message displayed on the UI.
```
ERROR: Failed to load help file: Not Found
```

**Comment by grayaii** [comment]
+1 on this.  I'm not sure if your issues will also answer my question on what is "conditional" and "action" checkmarks (in other words, once the help file is displayed, will the documentation explain what those check boxes are?): 

![hipchat](https://cloud.githubusercontent.com/assets/847072/15305833/a035f3fe-1b93-11e6-87dd-9d54334f7722.png)

**Comment by aldaris** [comment]
@mikelax sadly even if the link would have worked, the plugin wouldn't have displayed a description for the message templates, this should be now sorted. The bad URL was fixed via #76 btw.

@grayaii not sure where conditional and action is coming from, but the first checkbox is for "Notify Room", the second one is for "Text Format", see the column labels in bold at the top.
