### ISSUE TITLE
Notify of build result in Pipeline script

### ISSUE THREAD

**Issue by shishkin** [jenkinsci/hipchat-plugin#77]
I'm using Jenkins Pipeline and HipChat plugin 1.0.0. I've configured global HipChat plugin settings along with default notifications for build success and failure. When I run pipeline builds I see no notifications upon build completion (although test notification worked when I configured the plugin).

In the pipeline snippet generator I see how to send individual messages using the plugin (`hipchatSend color: 'YELLOW', message: '', room: '', sendAs: '', server: '', token: '', v2enabled: true`), but I don't see how to enable intelligent hipchat notifications that take build result into account. I don't want to write it in Pipeline DSL language as I suppose that's what this plugin already does, at least for normal non-pipeline builds.

Please let me know if I'm missing some configuration step or using the plugin wrong.

**Comment by dsmorse** [comment]
I'm having the same issue, but maybe it's me, I would have thought it was an issue with the pipeline plugin https://github.com/jenkinsci/build-pipeline-plugin not the hipchat plugin

**Comment by dsmorse** [comment]
This article helped by solve my notification issues: https://jenkins.io/blog/2016/07/18/pipline-notifications/

**Comment by shishkin** [comment]
Thanks, looks like a possible workaround. I didn't expect try-catch would work for multi-stage pipeline.

**Comment by aldaris** [comment]
I don't really see a way around this I'm afraid. The pipeline plugin can't have post build tasks from what I can see, and I couldn't really find a way to expose the underlying build/run to the script either.
You should be able to configure the HipChat plugin for a build job that you execute as part of the pipeline, but it would certainly not reflect the overall status of the pipeline itself.
