### ISSUE TITLE
Job display name is ignored

### ISSUE THREAD

**Issue by jakub-bochenski** [jenkinsci/hipchat-plugin#78]
Jenkins allows to set a more human-friendly[ "display name"](https://issues.jenkins-ci.org/browse/JENKINS-11762) attribute.
I think it should be used (or at least available as a variable) in notifications

**Comment by aldaris** [comment]
$JOB_DISPLAY_NAME is already implemented. Did you mean full display name?

**Comment by jakub-bochenski** [comment]
That's nice, but I couldn't find it before. In fact I only see it mentioned in the changelog ("JOB_DISPLAY_NAME macro is now available, should contain the project's display name similarly to pre 0.1.9 notifications (JENKINS-27712)")... any chance for a macro reference list?

**Comment by aldaris** [comment]
For the next version it will be duplicated to the default notification and job notification settings as well, so hopefully it will be more useful in the future. Until then, here's a shortcut: https://github.com/jenkinsci/hipchat-plugin/blob/master/src/main/webapp/help-projectConfig-hipChatMessages.html
