### ISSUE TITLE
Feature request: 'unstable back to normal' and 'failed back to normal'

### ISSUE THREAD

**Issue by rall** [jenkinsci/hipchat-plugin#79]
It would be awesome to have two 'back to normal' states: one for previously failed builds, and one for previously unstable builds.

**Comment by aldaris** [comment]
Apologies, but I don't really see what value this differentiation would add. Either way it's gonna be happy times for the Back To Normal notification. :)

**Comment by rall** [comment]
The value would be this: we want to notify on builds that are back to normal after a failure, but we don't want notifications on jobs that were previously only unstable.
