### ISSUE TITLE
Configurable glances to show individual job status and/or summary of jobs 

### ISSUE THREAD

**Issue by sgilroy** [jenkinsci/hipchat-plugin#80]
HipChat add-ons supports glances which are sticky and provide aggregate status information. It would It would be helpful if a companion HipChat add-on (perhaps associated with or independent from this Jenkins plugin) was created with support for glances so that we can either monitor individual jobs or the overall state of jobs from a room in HipChat.

Possible examples:
 - "12 jobs (2 failing)"
 - "Job server-unit-tests [failed]"
 - "Job client-deploy-staging [success]"

Guide:
https://developer.atlassian.com/hipchat/guide/glances

Example of an add-on that uses glances:
https://bitbucket.org/atlassianlabs/hipchat-uber-addon

**Comment by aldaris** [comment]
I very much agree that such an addon would be really great and quite helpful, however I don't believe that such an enhancement/new tool should be tracked within this plugin's bug tracker. If such extension becomes available though, would love to hear about it here though :)
