### ISSUE TITLE
Feature Request: Add template placeholder for git commit message

### ISSUE THREAD

**Issue by felixbarny** [jenkinsci/hipchat-plugin#81]
I'm using this plugin in combination with the gerrit plugin to post a notification when a new patch set is created. It would be great to be able to include the first line of the git commit message in the HipChat notification. Example:

```
$JOB_NAME $COMMIT_MESSAGE (<a href="$URL">Open</a>)
```

**Comment by aldaris** [comment]
NB: the commit message will be *empty* if there is no new changeset since the last build.
