### ISSUE TITLE
$URL variable not working in template

### ISSUE THREAD

**Issue by jukkasi** [jenkinsci/hipchat-plugin#84]
I'm not able to get any link to be generated using $URL in template. The link href is always empty. I have set Manage Jenkins -> Configure System -> Jenkins URL properly.

I'm running Jenkins ver. 1.658 and Jenkins HipChat plugin 1.0.0.

**Comment by aldaris** [comment]
What job type are you using?

**Comment by aldaris** [comment]
Can you test with logging level on FINE and/or with text (i.e. not HTML) format messages? The exact message should be printed to the logs then.

**Comment by jukkasi** [comment]
Job is a freestyle project configured by using Job DSL, with following plugins 

  - git
  - gradle
  - copyartifact
  - build-pipeline-plugin
  - delivery-pipeline-plugin
  - build-name-setter
  - cloudbees-folder
  - timestamper
  - envinject
  - xvfb
  - hipchat
  - ws-cleanup

**Comment by jukkasi** [comment]
Using plain text I get Testing nulljob/Deployment/job/Dev/job/E2ETest/8/ for $URL

**Comment by aldaris** [comment]
So what do  you have in ~/.jenkins/jenkins.model.JenkinsLocationConfiguration.xml exactly?

**Comment by aldaris** [comment]
I guess https://github.com/jenkinsci/docker/issues/138 could be related?

**Comment by jukkasi** [comment]
There was no jenkins.model.JenkinsLocationConfiguration.xml  on the disk.

Jenkins I have is set up by Ansible so I have never saved settings manually. When I go to settings the correct URL is visible in Jenkins settings but not on the disk which is very funny.

Now that I have saved settings manually all the settings appear on the disk and the problem is fixed.

**Comment by aldaris** [comment]
Good to hear. Closing ;)
