### ISSUE TITLE
Support for HipChat cards?

### ISSUE THREAD

**Issue by magicdude4eva** [jenkinsci/hipchat-plugin#85]
Is it possible to configure the HipChat message as a card rather than the normal HTML/Text message?

**Comment by aldaris** [comment]
Same request as https://issues.jenkins-ci.org/browse/JENKINS-32083

**Comment by aldaris** [comment]
FYI HipChat Card implementation is now in the works, an example (work in progress) card currently looks like:
![card](https://cloud.githubusercontent.com/assets/206692/22198399/4a41cc08-e14e-11e6-9ed6-9be5e8ed00b2.png)

To prevent frequent user requests about what should and should not be part of a given HipChat Card a new extension point will be created which will have full control over the contents of the cards sent with the notification.

**Comment by magicdude4eva** [comment]
@aldaris this is awesome - looks great!

**Comment by hlorofos** [comment]
Keep going! Can't wait any longer

**Comment by aldaris** [comment]
Initial card support is now complete. Closing issue.
