### ISSUE TITLE
Add macro for Build Description

### ISSUE THREAD

**Issue by jakub-bochenski** [jenkinsci/hipchat-plugin#88]
I think it would be useful -- if you set some information there it's probably relevant to include the same in notifications

Build description can be set using https://wiki.jenkins-ci.org/display/JENKINS/Description+Setter+Plugin or https://wiki.jenkins-ci.org/display/JENKINS/Groovy+Postbuild+Plugin

For now the workaround is to echo the desription to a file and use envinject plugin to make it into an Env; c.f. https://stackoverflow.com/questions/10413936 https://stackoverflow.com/questions/13277244

**Comment by aldaris** [comment]
With the integration of the token-macro plugin this will be available using the $JOB_DESCRIPTION token. You should be able to use this token with the upcoming 2.1.0 version.

**Comment by jakub-bochenski** [comment]
@aldaris $JOB_DESCRIPTION is the description of the job. I wanted *build* description :(

can you reopen this or sth?

**Comment by aldaris** [comment]
When I was trying to implement this I couldn't really see a build description on its own. If you could detail how to set the build description, that would be much appreciated.

**Comment by jakub-bochenski** [comment]
E.g. with the https://wiki.jenkins-ci.org/display/JENKINS/Groovy+Postbuild+Plugin you do:
```
manager.build.setDescription("Something about the build")
```
You can also use https://wiki.jenkins-ci.org/display/JENKINS/Description+Setter+Plugin in several ways

Other plugins, e.g. https://wiki.jenkins-ci.org/display/JENKINS/GitLab+Plugin set description based on the PR being built.

Finally you can also edit the build description manually, but that's not relevant for Hipchat notifications

**Comment by jakub-bochenski** [comment]
Double checked that using `$BUILD_DESCRIPTION` just results in literal "$BUILD_DESCRIPTION" output.

**Comment by aldaris** [comment]
Thanks for the reproduction steps, I was able to reproduce the issue and implement a new token macro.
