### ISSUE TITLE
Silently fails on untrusted certificate

### ISSUE THREAD

**Issue by amosshapira** [jenkinsci/hipchat-plugin#9]
When trying version 1.8 on Jenkins 1.577, the plugin fails silently when it can't verify the SSL certificate of the on-premises private HipChat server.

I think that the issue is that our HipChat server uses a wildcard certificate - e.g. *.company.com, which is properly signed by a certificate authority but many years ago I learned that Java doesn't support them properly.

It would be useful to have the plugin more verbose about why it failed, or even better - make it possible to trigger a test request.

**Comment by aldaris** [comment]
Resolved with 58126f3
