### ISSUE TITLE
Add placeholder for failed test names in HipChat messages

### ISSUE THREAD

**Issue by mdio** [jenkinsci/hipchat-plugin#90]
It would be nice to see which test failed without having to consult Jenkins for that.
I'm thinking of the names displayed on the //jenkins/job/MyJob/42/testReport/ page.
Of course not all of the failed but only the first 3 or so.

**Comment by aldaris** [comment]
With the integration of token-macro-plugin, this is now possible thanks to email-ext-plugin's $FAILED_TESTS macro. Should be available with version 2.1.0.
