### ISSUE TITLE
Need ability to turn off Blue Ocean links in HipChat messages

### ISSUE THREAD

**Issue by rickthepick** [jenkinsci/hipchat-plugin#92]
It seems that this issue "Blue Ocean UI support - the HipChat plugin should now generate URLs that are compatible with Blue Ocean (#82)" caused all links in HipChat messages to be Blue Ocean links.  For example the links begin with "/blue".  Only one of our many Jenkins users uses Blue Ocean so we would like to be able to configure the plugin so that the links in HipChat are non-blue.

**Comment by aldaris** [comment]
sigh, wasn't aware that blueocean can be configured on a per user basis..

**Comment by rickthepick** [comment]
I think after you install Blue Ocean everything remains the same with respect to the existing links, but now there is a "Blue Ocean" link at the top of the home page.  So our one Blue Ocean user can use that link and everything remains as it was for all the other users.

**Comment by higrow** [comment]
@rickthepick i think this would have to be implemented in [blueocean-display-url-plugin](https://github.com/jenkinsci/blueocean-display-url-plugin)

i had a similar problem (notification links for "regular" freestyle builds pointing to blueocean) and downgraded the plugin for that reason as temporary workaround.
 
there seems to be a issue for that though: https://issues.jenkins-ci.org/browse/JENKINS-39580

**Comment by aldaris** [comment]
Even then I'm not sure how could the HipChat plugin possibly determine what UI the end-user wants to see when clicking on a notification in a HipChat notification.
Sounds like the BlueOcean link needs to be stored in a new message variable and the default URL should just keep on pointing at the OOTB UI.

**Comment by rickthepick** [comment]
Thanks @higrow.  Yes I just downgraded the plugin.  I'll watch the issue you mention.

**Comment by rickthepick** [comment]
@aldaris perhaps there could be a checkbox for blue on a project basis.  It wouldn't need to be on a user basis for us.

**Comment by aldaris** [comment]
I'm really fed up with the settings now :)
Once there is a job based setting, people will ask for a global setting as well. I'm not that patient now :)

**Comment by rickthepick** [comment]
Yeah being able to set the default at the top level and then being able to override that at a project level would be the way to go I think.

**Comment by higrow** [comment]
@rickthepick but i think i's be a issue of the blueocean-display-url-plugin, not the hipchat plugin

it just captures all the links and would lead to the same problem for everything using the display-url api.

**Comment by aldaris** [comment]
I'll just make it a message template variable and then that feature will be available for free: if you need blueocean URLs everywhere then configure the default message template to use URL_BLUE_OCEAN variable.

**Comment by aldaris** [comment]
@higrow the problem is that the HipChat notification doesn't belong to a particular user, so you can't check if BO is enabled for that person or not. Anyone who clicks on the notification wants to see their own UI, I think that could be achieved if the BO URL could capture and redirect requests to the BO UI if BO is enabled for that user.

**Comment by higrow** [comment]
i may be wrong but i don't find any option to configure it on the user-level, i think that @rickthepick meant that one user in a specific project uses blue ocean.

**Comment by rickthepick** [comment]
that's what i mean.  I'm not aware that blue ocean can be turned-on for a particular user.

**Comment by rickthepick** [comment]
in our case all the projects associated with that user would be blue ocean projects, so being able to specify it on a project basis would be fine.

**Comment by aldaris** [comment]
I couldn't really find a BlueOcean specific project type. Did you refer to Pipeline builds? In my understanding the pipeline projects can be accessed using the original UI as well.

**Comment by rickthepick** [comment]
@aldaris sorry, I didn't mean to imply that there is something called a blue ocean project, I just meant that we are setting up new projects that we consider blue ocean projects and will use the blue ocean theme when interacting with them.  For these types of projects we would want the HipChat links to have blue ocean links.
