### ISSUE TITLE
Security warnings about the Jenkins headshot image

### ISSUE THREAD

**Issue by reist** [jenkinsci/hipchat-plugin#94]
Hipchat uses https, yet the image for Jenkins is given as "http://bit.ly/2ctIstd".
This causes warnings in Firefox and Chromium, and https://bit.ly/2ctIstd works just as well.
This is the only insecure element for me in Hipchat, and it would be nice to get a green lock instead of a yellow one.

**Comment by aldaris** [comment]
Nice find. I blame it on bit.ly that generates http URL by default :(

**Comment by aldaris** [comment]
Should be fixed in the upcoming 2.1.1 version.
