### ISSUE TITLE
Cannot select credentials

### ISSUE THREAD

**Issue by kevcodez** [jenkinsci/hipchat-plugin#95]
Navigating to Manage Jenkins -> Configure System and look for Global HipChat Notifier Settings

I have four different credentials defined, however, the dropdown for the credentials is empty. Every other credential selection works. Running the latest version of the Hipchat Plugin with the Jenkins 2.32.2.

**Comment by aldaris** [comment]
Are you using "secret text" kind of credential? Did you create the Credential at the HipChat settings?

**Comment by kevcodez** [comment]
I did create the credentials at the Hipchat settings. I am using username + password authentication.

**Comment by aldaris** [comment]
username & password will not work, you'll need an OAuth2 token, see docs: https://wiki.jenkins-ci.org/display/JENKINS/HipChat+Plugin

**Comment by kevcodez** [comment]
Thanks, it is working as expected, sorry for creating an issue ;)

**Comment by aldaris** [comment]
Good to hear it's working :)
