### ISSUE TITLE
Error 503 in Test Configuration and Pipeline execution.

### ISSUE THREAD

**Issue by david-romero** [jenkinsci/hipchat-plugin#97]
Hi,

I am trying to install the plugin for hipchat but when i'm doing a test of shipment I get the following message: "Unexpected response code from HipChat: 503". When performing the test from the pipeline I get the same error.

I have made a test with a REST tool and if I can send the message to hipchat.

I searched the documentation for the HipChat api and a 503 error code indicates service is temporarily unavailable.

What could be the problem?

Attached some screenshots.

Thank you very much

![configuration](https://cloud.githubusercontent.com/assets/8822102/23124911/a9cbcd04-f76f-11e6-816b-6ab755e2ed51.png)
![evidence](https://cloud.githubusercontent.com/assets/8822102/23124912/a9d23680-f76f-11e6-9ddd-e8c07402c085.png)

Regards

**Comment by aldaris** [comment]
Do you see a more detailed error message in your container/Jenkins logs?

**Comment by david-romero** [comment]
I have searched in <JenkinsDir>/logs and <JenkinsDir>/plugins/hipchat and I have not found anything.

Any log where I could look?

**Comment by aldaris** [comment]
If you are running Jenkins on Tomcat: $TOMCAT_HOME/logs/catalina.out

**Comment by david-romero** [comment]
Sorry, I already found the problem.

In the field "HipChat Server" you can not put the "http: //".

You must enter <hipchat-server> .hipchat.com and not http: // <hipchat-server> .hipchat.com

Thank you very much and sorry for the big mistake.

**Comment by aldaris** [comment]
The plugin docs already say that the server is accessed over HTTPS only, but the help text doesn't explicitly say this. I will update the help text to include this information.
