### ISSUE TITLE
Global Default Notifications are not inherited

### ISSUE THREAD

**Issue by ShortCipher42** [jenkinsci/hipchat-plugin#99]
Currently I have Global HipChat Notifier Settings set up with Default Notifications.  None of my jobs have any HipChat notifier configurations set up.

According to documentation for global configurations: "Default notifications: Configure the default set of notifications. These will be used when there is no notification configured at the job level."

As a result, I would expect my jobs to all use the Global notification settings.  None of them do.  The only jobs with functional notifications are ones that I have set on an individual job level.

**Comment by ShortCipher42** [comment]
This is also using multi-configuration projects.  I am not sure if that is relevant.

**Comment by aldaris** [comment]
Have you added the HipChat notifications post build task to the job?

**Comment by ShortCipher42** [comment]
I was under the impression that doing so would be adding a notification, and would override the Global configurations.  How can I apply the post build task to all jobs without individually going into each's configuration?

**Comment by aldaris** [comment]
Without the Post Build Task the plugin never gets invoked, so it can't send out the default notifications either. I will update the help message to clear this up.

To change all jobs I would probably use the scriptler plugin and write a Groovy script to add the post build task to the existing list of tasks.

**Comment by aldaris** [comment]
Reopening issue so that I can track the need to update the help text.
